/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package fork.test

import org.testcontainers.containers.GenericContainer
import org.testcontainers.containers.wait.strategy.Wait
import spock.lang.Specification

class AppTest extends Specification {

    def "Container starts"() {
        setup:
        GenericContainer jdk = new GenericContainer<>("winamd64/openjdk:11.0.9.1-jdk-windowsservercore-1809")

        jdk.withCommand("java", "-version")
        jdk.start()

        jdk.waitingFor(Wait.forLogMessage("version", 1))

        expect:
        true
    }
}
