/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package fork.test


import groovy.util.logging.Slf4j
import spock.lang.Specification

@Slf4j
class AppTest extends Specification {

  def "Check Collector is UP"() {
    when:
    new URL("http://localhost:55680").openStream().transferTo(System.out)
    then:
    noExceptionThrown()

  }
}
